### ISSUE TITLE
Long delay updating file name when navigating between files

### ISSUE THREAD

**Issue by HolbyFPV** [AlexGirardDev/HarpoonIJ#6]
Thanks again for the awesome work on the plugin.  The latest update has been a dream to use! 😄 

I'm noticing a pretty big delay when switching between harpooned files.  I use tabs disabled.  Are you seeing this big of a delay?

https://gyazo.com/b93ad05edd8bbecdcb7debb28d72ec85

To rule out an IDE issue, I checked other ways of switching files like the fuzzy finder and recent file switcher.  These seem to have some delay, but not nearly as much as using harpoon.  

Although seeing there is still some delay with the raw IDE feature, this is probably an IDE bug.  Just looking for confirmation that it's not a local issue with my machine.

**Comment by AlexGirardDev** [comment]
Hey,

i don't exprience any delay on my end, i can switch back and forth between files pretty much as fast as i can press the keys. I also have a very fast computer with a high end SSD so that could be why i don't have any delay.

I think currentyl i am just naively loading the file every time you press a hotkey. I have a suspcitian this is maybe loading the file from disk every singe time instead of switching to an already open tab with that file loaded

I don't have time right now but in the near future i will see if i can make this file switching smarter / hopefuly resolve your delay as that seems very frustarting.

**Comment by HolbyFPV** [comment]
Apologies, I worded my OP very poorly.  The file content switch happens instantly.  The breadcrumb showing the filename at the bottom switches almost instantly too.  But the filename at the top does not.  

After spending a few more days with it, it doesn't seem to be related to HarpoonIJ at all so feel free to close this issue.  I am still curious if you see the same delay I'm seeing with that top bar component.  Would indicate to me if there some issue with my jetbrains config.

**Comment by HolbyFPV** [comment]
Confirmed it with Jetbrains.  Reproduceable issue on their end.
